### ISSUE TITLE
[BUG] linter fails when env variable is non-string

### ISSUE THREAD

**Issue by nirav24** [stackrox/kube-linter#136]
**System info:**
 - OS: MaxOS

**Describe the bug**
k8s requires env variable to be of type string. when non-string value is set as env, kube-linter fails with the below error
```
Warning: no valid objects found.
```

**To Reproduce**
- put below yaml under **dummy** dir
- run `kube-linter lint ./dummy`

**Sample YAML input**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    label1: content
spec:
  replicas: 1
  selector:
    matchLabels:
      label1: content
  template:
    metadata:
      labels:
        label1: content
    spec:
      containers:
        - name: test-container
          image: "image/image:tag"
          env:
          - name: TEST
            value: 1
```
**Expected behavior**
Linter should give a proper error message something like 

**Only type "string" is allowed.**
