### ISSUE TITLE
[BUG] Serviceaccount not found error

### ISSUE THREAD

**Issue by sai1621** [stackrox/kube-linter#137]
**System info:**
 - MacOS

**Describe the bug**
Throwing a `non-existent-service-account` error even when the serviceaccount exists

**To Reproduce**

1. Create a serviceaccount : 

`kubectl create sa lint-test-sa`

2. Create a deployment.yaml file with the content below :

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-linter-test
spec:
  replicas: 1
  selector:
    matchLabels:
      label1: content
  template:
    metadata:
      labels:
        label1: content
    spec:
      serviceAccountName: lint-test-sa
      containers:
        - name: kube-linter-test-container
          image: "image/image:tag"
```

3. Run the `kube-linter` :

`kube-linter templates deployment.yaml`

```
templates.yaml: (object: <no namespace>/kube-linter-test apps/v1, Kind=Deployment) serviceAccount "lint-test-sa" not found (check: non-existent-service-account, remediation: Make sure to create the service account, or to refer to an existing service account.)
```

**Expected behavior**
The linter should show no errors. I am using kube-linter version 0.1.6.
