### ISSUE TITLE
[FEATURE_REQUEST] Do not warn about dangling service linked to deployment or statefulset without a pod

### ISSUE THREAD

**Issue by tspearconquest** [stackrox/kube-linter#179]
**Description of the problem/feature request**
Service definitions with a label selector matching a deployment or statefulset definition without any pod definition are generating a dangling service warning in kube-linter because the dangling service check appears to only concern itself with pods.

**Description of the existing behavior vs. expected behavior**
Consider the following service definition:
```
apiVersion: v1
kind: Service
metadata:
  name: appnameA
  labels:
    app: appnameALabel
```
And the following deployment definition:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appnameA
  labels:
    app: appnameALabel
```

When running kube-linter, we get the following:
```
kubernetes/60-services/appnameA-svc.yaml: (object: <no namespace>/appnameA /v1, Kind=Service) no pods found matching service labels (map[app:appnameALabel]) (check: dangling-service, remediation: Make sure your service's selector correctly matches the labels on one of your deployments.)
```

**Additional context**
The warning message is technically correct, there is no pod which matches the service label. However this is not a dangling service, and should not generate a warning. We currently annotate for this but we are looking to improve the kubernetes definitions and remove annotations where possible in order to help us not miss any potential avenues that could be later leveraged by malicious code.

**Comment by viswajithiii** [comment]
Hi @tspearconquest, thanks for filing this issue. I will admit I've never seen a deployment definition without a pod spec. How does that work? If you `kubectl create` that, will it create pods with some default spec?

**Comment by tspearconquest** [comment]
Hey Viswajith, I checked in the namespace just now. It looks like it does create a pod with the same spec (or nearly the same, as I could not see any difference) as the deployment.

**Comment by viswajithiii** [comment]
But how does it know what image to create, for example?

**Comment by tspearconquest** [comment]
The definition I provided was only a partial example for demonstration purposes.

In our full setup, we have a CI pipeline which builds the image from our Dockerfile and the app source code, then runs kube-linter, and then deploys the app to a kubernetes cluster. The kubernetes definition is relatively simple but I cannot share the full spec as it is internal to my organization.

**Comment by viswajithiii** [comment]
Ohh, got it. I was really confused. 😅 

Here's a very minimal example I put together. In this example, `kube-linter` does _not_ flag the service as a dangling service. You can see it does not find an error.

```
kube-linter lint - <<EOF --do-not-auto-add-defaults --include dangling-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx:latest
        name: nginx 
---
apiVersion: v1
kind: Service
metadata:
  name: appnameA
  labels:
    app: test
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: test
  type: ClusterIP
EOF
```

**Comment by viswajithiii** [comment]
Can you help me modify this example so as to reproduce the problem you're seeing?

**Comment by tspearconquest** [comment]
Hi Viswajith,

When I run kube-linter in the way you have done with a heredoc, using our internal definitions, it is not reporting the issue.

However, when I place them in separate files (deployment.yaml and service.yaml, for example) and run:
`kube-linter lint .` then I can see the error.

**Comment by viswajithiii** [comment]
Hmm, it should understand that it is part of the same context, and it does. I just tested it that way:

```
viswa:~/kube-linter-demo/yamls/temp (docker-desktop)$ ls
dep.yaml  svc.yaml
viswa:~/kube-linter-demo/yamls/temp (docker-desktop)$ cat dep.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx:latest
        name: nginx 

viswa:~/kube-linter-demo/yamls/temp (docker-desktop)$ cat svc.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx:latest
        name: nginx 
---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: test
  type: ClusterIP

viswa:~/kube-linter-demo/yamls/temp (docker-desktop)$ kube-linter lint . --do-not-auto-add-defaults --include dangling-service
KubeLinter 0.2.1-0-gc53952b8e3

No lint errors found!
```

**Comment by tspearconquest** [comment]
Your svc.yaml contains the deployment a second time...

**Comment by viswajithiii** [comment]
> Your svc.yaml contains the deployment a second time...

Ah, my bad. I just fixed and retried. Same result though...

```
**viswa:~/kube-linter-demo/yamls/temp (docker-desktop)$ ls
dep.yaml  svc.yaml
viswa:~/kube-linter-demo/yamls/temp (docker-desktop)$ cat dep.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx:latest
        name: nginx 

viswa:~/kube-linter-demo/yamls/temp (docker-desktop)$ cat svc.yaml 
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: test
  type: ClusterIP

viswa:~/kube-linter-demo/yamls/temp (docker-desktop)$ kube-linter lint . --do-not-auto-add-defaults --include dangling-service
KubeLinter 0.2.1-0-gc53952b8e3

No lint errors found!
```
