### ISSUE TITLE
[BUG] SARIF Output log adds an additional line which cannot be parsed by GitHub's upload-sarif action for code alerts. 

### ISSUE THREAD

**Issue by dev0701** [stackrox/kube-linter#193]
**Describe the bug**

When using KubeLinter on self hosted runners with the `--format=Sarif ` tag, the output log produced has a line at the end `Error: Found 'x' lint errors`.

the GitHub Action `codeql-action/upload-sarif` throws an error while parsing the `.sarif` JSON. An example of the error is attached below:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/42981883/124963505-e8264f00-dfed-11eb-87ab-e1679f81cc30.png">

This issue can be fixed when the `.sarif` output does not have the line `Error: Found 'x' lint errors`

**To Reproduce**

In the action.yml file: 

```
...
- name: Lint files
      run: |
        set -u
        set +e
        if [ -z ${{ inputs.config }} ]; then
          CONFIG=""
        else
          CONFIG="--config ${{ inputs.config }}"
        fi
        ./kube-linter $CONFIG lint --format=sarif ${{ inputs.directory }} 2>&1 | tee -a output.sarif
        exit ${PIPESTATUS[0]}
  shell: bash
```

In the workflow:

```
...
- uses: actions/checkout@v2
- name: Lint Repository 
   uses: github-actions-for-cicd/custom-kube-linter-action@main
   with:
        directory: sample/invalid-yaml
        output-file: output.sarif
- name: Show sarif
   if: always()
   run: |  
      cat output.sarif
- name: Upload result to GitHub Code Scanning 
   if: always()
   uses: github/codeql-action/upload-sarif@v1
   with:
       sarif_file: output.sarif
...
```

When the action runs. The error should appear when the upload-sarif action runs. 

**Expected behavior**

Expected end of .sarif file: 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/42981883/124965272-ea89a880-dfef-11eb-99ef-69d2375e4881.png">

Actual end of .sarif file:
<img width="643" alt="Screen Shot 2021-07-08 at 1 22 45 PM" src="https://user-images.githubusercontent.com/42981883/124965196-d5ad1500-dfef-11eb-93dd-bbd345c97321.png">

The output file should be parseable for GitHub Code Scanning, and not have the line `Error: Found 'x' lint errors`
