### ISSUE TITLE
[BUG] pre-commit documentation incorrect

### ISSUE THREAD

**Issue by mjpieters** [stackrox/kube-linter#222]
**Describe the bug**
The documentation tells you to download the `.pre-commit-hooks.yaml` file; from https://docs.kubelinter.io/#/using-kubelinter?id=using-kubelinter-with-the-pre-commit-framework:

> Download the `.pre-commit-hooks.yaml` file in the Git repository in which you want to install the KubeLinter pre-commit hooks:
> 
> ```sh
> curl -O https://raw.githubusercontent.com/stackrox/kube-linter/main/.pre-commit-hooks.yaml
> ```

This is not how pre-commit usually works, nor is the above necessary at all. You specify the *repository* in your local `.pre-commit-config.yaml` file, instead.

**Expected behavior**
The documentation should be corrected to follow the [canonical instructions on adding plugins with a GitHub repository](https://pre-commit.com/#pre-commit-configyaml---repos).

You add a section to your `.pre-commit-config.yaml` file referencing the `kube-linter` repository, plus a specific release, plus the files that should trigger the hook when changed. E.g. to run the current release of kube-linter on all changed yaml files in a repository, use:

```yaml
  - repo: https://github.com/stackrox/kube-linter
    rev: 0.2.4
    hooks:
      - id: kube-linter
        args: [lint]
```

The hook configuration already sets `types`, but you could use a `files:` regex pattern to limit the hook to a specific directory containing your resources or chart.

A local configuration file can be configured using additional entries in the `args` list, e.g. `args: [lint, --config, kubelinter-config.yaml]`

**Additional context**
Rather than require that users must always set `args: [lint]`, consider giving your hooks configuration [an `entry` that includes `lint`](https://pre-commit.com/#hooks-entry):

```yaml
- id: kube-linter
  name: KubeLinter
  description: This hook installs (using Go) and runs the KubeLinter utility to lint Helm charts and Kubernetes YAML files.
  entry: kube-linter
  language: golang
  types: [yaml]
  entry: kube-linter lint
```

This does assume that the linter is generally used without specifying the specific resource.

Also, please consider adding Helm chart versions of the hooks, with [`pass_filenames: false`](https://pre-commit.com/#hooks-pass_filenames); the hook would need to be given the path to `Chart.yaml` in `args`, but would run whenever any of the files in the chart changed:

```yaml
- id: kube-linter-helm
  name: KubeLinter (Helm)
  description: This hook installs (using Go) and runs the KubeLinter utility to lint Helm charts. Requires that `args` names the chart(s) to lint when the hook matches.
  entry: kube-linter lint
  language: golang
  pass_filenames: false
  types: [yaml]


- id: kube-linter-helm-system
  name: KubeLinter (Helm) System
  description: This hook runs the KubeLinter utility that exists already on the system to lint Helm charts. Requires that `args` names the chart(s) to lint when the hook matches.
  entry: kube-linter lint
  language: system
  pass_filenames: false
  types: [yaml]


- id: kube-linter-docker
  name: KubeLinter (Helm) Docker
  description: This hook runs kube-linter using the project's official docker image
  language: docker_image
  entry: stackrox/kube-linter:latest /kube-linter lint
  pass_filenames: false
  types: [yaml]
```
