### ISSUE TITLE
[BUG] --format 'plain' gives no warnings but sarif/json does

### ISSUE THREAD

**Issue by frerikandriessen** [stackrox/kube-linter#228]
**System info:**
 - OS: Windows (git bash) & Linux (stackrox alpine docker image)

**Describe the bug**
Whenever I select 'plain' as --format, it will say it hasn't found errors. Checking it with json or 

**To Reproduce**
Using this configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-kube-linter-configmap
data:
  configmap.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: no-name
    data:
      test: big-test
```

gives 
```
$ kube-linter lint --format plain configmap.yaml
KubeLinter 0.2.4

No lint errors found!
```

while the other commands do give output (unsure if it's the same warnings that it emits, could check that if you'd like)

sarif
```
$ kube-linter lint --format sarif configmap.yaml
{"version":"2.1.0","$schema":"ht... #etc, cutoff for brevity
```

json
```
$ kube-linter lint --format json configmap.yaml
{"Checks":[{"name":"dangling-service","description":"Indicates when... #etc, cutoff for brevity
```

**Expected behavior**
For plain to have the same errors/warnings, just formatted differently.
