### ISSUE TITLE
Support OpenShift objects

### ISSUE THREAD

**Issue by viswajithiii** [stackrox/kube-linter#25]
Support checks on OpenShift objects. Suggestions we [got](https://www.reddit.com/r/kubernetes/comments/jjpqn5/introducing_kubelinter_an_open_source_linter_for/gafycbk) were to look at `imagestreams`, `deploymentconfigs`, `buildconfigs` and `routes`.

**Comment by mancubus77** [comment]
+1 for the feature

**Comment by garethahealy** [comment]
@viswajithiii ; any plans to support `Template`? in the same way, k8s `List` and `helm` are.

**Comment by viswajithiii** [comment]
> @viswajithiii ; any plans to support `Template`? in the same way, k8s `List` and `helm` are.

Hmm, I'm not familiar with `Template`. Can you elaborate on how it's used?

**Comment by garethahealy** [comment]
They are a way to provide a simple template for a list of resources (_pre-helm, started in OCP3_). Obviously, customers are migrating to better/other ways, but they are still used by a large number of customers.
- https://docs.openshift.com/container-platform/4.8/openshift_images/using-templates.html

```
cat << EOF > template.yaml
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "database,nosql"
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: redis-master
  spec:
    containers:
    - env:
      - name: REDIS_PASSWORD
        value: ${REDIS_PASSWORD}
      image: dockerfile/redis
      name: master
      ports:
      - containerPort: 6379
        protocol: TCP
parameters:
- description: Password used for Redis authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: REDIS_PASSWORD
EOF

oc process --local -f template.yaml
```
