### ISSUE TITLE
[FEATURE_REQUEST] Node Affinity Check

### ISSUE THREAD

**Issue by TANguyen1893** [stackrox/kube-linter#257]
**Description of the problem/feature request**
Similar to the check for the pod affinity, it would be nice to have one for the definition for node affinity to ensure pods are scheduled to a particular node pool. It could take as input a list of node pool values and the manifest files must include a value from that input list.
```yaml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - nodePoolA
``` 

**Description of the existing behavior vs. expected behavior**
This is not currently supported out of the box.

**Additional context**
I could try to create a PR for this feature, however I am not a seasoned Go developer.
