### ISSUE TITLE
Support all HPA versions

### ISSUE THREAD

**Issue by mrunesson** [stackrox/kube-linter#287]
**Description of the problem/feature request**
Current implementation of template hpa-minimum-replicas only support v2beta1 of horizontalpodautoscaler. There is also a stable version v1 and a newer beta v2beta2. It would be valuable to support these two versions too.

**Description of the existing behavior vs. expected behavior**
This is tested on head of main branch.

The following is generating the expected warning of too few replicas.
```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: demo
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app
  targetCPUUtilizationPercentage: 50
```

Changing the version to v1 lead to a false statement of `No lint errors found!`:
```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app
  targetCPUUtilizationPercentage: 50
```

The expected output of this would be:
```text
hpa.yaml: (object: aardvark-demo-develop/aardvark-demo autoscaling/v2beta1, Kind=HorizontalPodAutoscaler) object has 2 replicas but minimum required replicas is 3 (check: hpa-minimum-three-replicas, remediation: Increase be number of replicas in the HorizontalPodAutoscaler to at least three to increase fault tolerance.)
```

Same for v2beta2.
