### ISSUE TITLE
[FEATURE_REQUEST] Add support to check dnsConfig options

### ISSUE THREAD

**Issue by weixiongny** [stackrox/kube-linter#354]
**Description of the problem/feature request**
Add support to check dnsConfig options, which is for customized dns setting on pods.

**Description of the existing behavior vs. expected behavior**
After kubernetes 1.14, `dnsConfig` field can be used to override the default dns setting for pods. Especially for our applications in large kubernetes cluster, we need `ndots:2` setting under `options` field. It will be nice that kube-linter has a template/check for dnsConfig options, e.g. some check yaml example
```
name: "dnsconfig-options"
description: "Alert on deployments that have no specified dnsconfig options"
remediation: >-
  Specify dnsconfig options in your pod specification to ensure the expected dns setting on the pod.
  Refer to https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config for details.
scope:
  objectKinds:
    - DeploymentLike
template: "dnsconfig-options"
params:
  Key: ndots
  Value: "2"
```

**Additional context**
* some refer link https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
* It is not a kube-linter default built-in check.
