### ISSUE TITLE
[BUG] Lint fails on no-anti-affinity check in 0.3.0 where it succeeded in 0.2.6

### ISSUE THREAD

**Issue by tspearconquest** [stackrox/kube-linter#369]
**System info:**
 - OS: Linux

**Describe the bug**
`/dir/lintme.yaml: (object: linkerd/linkerd-destination apps/v1, Kind=Deployment) anti-affinity's topology key does not match "failure-domain.beta.kubernetes.io/zone" (check: no-anti-affinity, remediation: Specify anti-affinity in your pod specification to ensure that the orchestrator attempts to schedule replicas on different nodes. Using podAntiAffinity, specify a labelSelector that matches pods for the deployment, and set the topologyKey to kubernetes.io/hostname. Refer to https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity for details.)`

The pod being checked here has the below affinity rules:

```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - web
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - web
            topologyKey: kubernetes.io/hostname
```
As you can see, we have 2 different topologyKey values in use here. This error started happening after we upgraded kube-linter to v0.3.0. I did some searching and I found #318 is likely the cause here.

I'm not sure why the output tells me to set the topologyKey to `kubernetes.io/hostname` when the failure also clearly states `anti-affinity's topology key does not match "failure-domain.beta.kubernetes.io/zone"` -- The remediation text should match the failure, but it doesn't, so it's not clear here which one of the anti affinity rules is the problem, or what the proper solution is.

**To Reproduce**
Set affinity rules as above on a deployment manifest and then lint it with kube-linter.

**Sample YAML input**
See above

**Expected behavior**
Lint successfully passes like it did in 0.2.6
