### ISSUE TITLE
Add more CI/CD Integration examples 

### ISSUE THREAD

**Issue by mclarkex** [stackrox/kube-linter#493]
**Description of the problem/feature request**
Provide more examples of how to integrate kube-linter into other CI/CD tools for wider adoption and usage. 

**Description of the existing behavior vs. expected behavior**

Current documentation is limited regarding how to integrate with other CI/CD tools. 

I've provided a working example of getting Kubelinting working for Kubernetes and Helm within [Concourse CI](https://concourse-ci.org/) Concourse is a popular Go-based CI tool used at a lot of large organisations. 

1. Create a new resource_type:

```yaml

resource_types:
 - name: kubelinter-image
    type: docker-image 
    source: 
      repository: stackrox/kube-linter 
      tag: latest
```

2. Create a resource where your Kubernetes for helm files are stored 
```yaml

- name: platform-code
  type: git
  icon: github
  source: 
    uri:   git@github.com:/orginisation/platform-code.git
    branch: main
    private_key: ((xxxxxx)) #Your SSH key 

```

2. Create a new job pulling in your Kubernetes or helm files 

```yaml
jobs:
- name: kube-linting
  plan:
    - get: platform-code #Your repository with 
      trigger: true 
    - task: kube-linting
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: stackrox/kube-linter 
            tag: latest
        inputs:
          - name: platform-code
        run: 
          path: /kube-linter 
          args: 
          - lint
          - platform-code/kubernetes/kubernetes-manifiest.yaml
```

- The syntax within Concourse requires kube-linter arguments to be passed on two separate lines 

**Sntax error**
![image](https://user-images.githubusercontent.com/51784241/219427395-0edb0ab6-0000-4d36-9da4-e220af3d0522.png)

**Working Example Output:**
![image](https://user-images.githubusercontent.com/51784241/219425552-154f15ee-efec-46c3-b858-3ed4506e748a.png)

**Additional context**

This is a relatively simple PR, but if accepted I will raise a PR with Concourse to add kube-linter to a list of valid resource types as outlined here: https://github.com/concourse/resource-types and here https://resource-types.concourse-ci.org/

Will provide an example for Azure DevOps aswell.
