### ISSUE TITLE
Possibility to Add Scope to CustomChecks

### ISSUE THREAD

**Issue by mstoetzer** [stackrox/kube-linter#88]
Is it possible to add a scope to a CustomCheck?

```
customChecks:
  - name: required-annotation-responsible
    template: required-annotation
    scope: [{'DeploymentLike'}]
    remediation: Please set annotation 'responsible'
    params:
      key: responsible
```

So, that the scope that comes from the template gets overwritten. Is such thing possible (and wanted)?

**Comment by mstoetzer** [comment]
Nevermind, diggin into the code let me find out:

```
customChecks:
  - name: required-annotation-responsible
    template: required-annotation
    scope:
      objectKinds:
        - DeploymentLike
    remediation: Please set annotation 'responsible'
    params:
      key: responsible
```
