### ISSUE TITLE
[FEATURE_REQUEST] Question: How to disable privileged check for initcontainers

### ISSUE THREAD

**Issue by bbkgh** [stackrox/kube-linter#928]
Hi. I want to disable privileged  check for initcontainers but containers must be checked by that. I there any solution for this? sth like:

```
customChecks:
  - name: privileged-containers-just-containers
    template: privileged
    scope:
      fieldSelector: "spec.containers"
```
