### ISSUE TITLE
[BUG] readOnlyRootFilesystem set to true, but no-read-only-root-fs error still triggers

### ISSUE THREAD

**Issue by likered** [stackrox/kube-linter#99]
**System info:**
 - OS: [e.g. Linux? MaxOS? Windows?]

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"

**Describe the bug**
A clear and concise description of the bug.

Setting `readOnlyRootFilesystem` to true under Deployment.spec.template.spec.securityContext still results in the check `no-read-only-root-fs` triggering.

**To Reproduce**

1. Add securityContext block containing `readOnlyRootFilesystem: true` under Deployment.spec.template.spec.securityContext
2. Run `kube-linter lint validation/`
3. Error pops up
```
validation/deploy.yaml: (object: default/validation apps/v1, Kind=Deployment) container "validation" does not have a read-only root file system (check: no-read-only-root-fs, remediation: Set readOnlyRootFilesystem to true in your container's securityContext.)
```

**Sample YAML input**
If applicable, sample YAML input which reproduces the issue.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation
  namespace: default
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
```

**Expected behavior**

The `no-read-only-root-fs` check should not pop up.

**Screenshots**

**Additional context**
